name: hydas_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - flet==0.28.3
  - richdem
  - rasterio
  - geopandas
  - scikit-image
  - networkx
  - shapely
  - fiona
  - pandas
  - numpy
  - scipy
  - cupy
  - pip:
      - pydantic
      - sqlalchemy
      - geoalchemy2
      - pyshp
      - beautifulsoup4
      - lxml
      - seaborn
      - openpyxl
      - fpdf2
      - geopy
      - pmdarima
      - tabulate
      - statsmodels
      - pyarrow
      - psutil
      - gputil
      - tqdm
